version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: event_manager_app
        restart: always
        environment:
            - DB_CONNECTION=pgsql
            - DB_HOST=postgres
            - DB_PORT=5432
            - DB_DATABASE=event_manager
            - DB_USERNAME=event_user
            - DB_PASSWORD=secret_password
        volumes:
            - ./:/var/www
        expose:
            - "9000"
        depends_on:
            - postgres

    nginx:
        image: nginx:alpine
        container_name: event_manager_nginx
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - app

    postgres:
        image: postgres:14
        container_name: event_manager_postgres
        restart: always
        environment:
            - POSTGRES_DB=event_manager
            - POSTGRES_USER=event_user
            - POSTGRES_PASSWORD=secret_password
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
